services:
  - type: web
    name: ultimate-summarization-api
    env: docker
    rootDir: .
    dockerCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false